---
title: "Model description"
author: "Florian D. Schneider"
date: "December 1st, 2016"
output:
  pdf_document:
    fig_height: 4
    fig_width: 6
  html_document:
    keep_md: yes
fontsize: 12pt
geometry: margin=1.4in
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}

# provides parallel backend
library(foreach)
library(doSNOW)

workstation <-  list(host = "162.38.184.118", user = "florian",
                     rscript = "/usr/lib/R/bin/Rscript",
                     snowlib = "/usr/lib/R/library")

workerlist <- c(rep("localhost", times = 7)) 

cl <- makeSOCKcluster(workerlist,  outfile='out_messages.txt')

registerDoSNOW(cl)


```



We implement the equations for plant mortality and growth outlined above in a pair-approximation model of a spatially-explicit cellular automata framework. We contrast this to a model that does not account for spatial structure and assumes that the local neighborhood cover of plants is equal to the global vegetation cover, i.e. a mean field model. 

Subsequently, we describe a basic form of the model that has been used by Noy-Meir and substitute it's elements with specific models of local plant-plant interactions. A system of ordinary differential equations is implemented in the framework of a mean-field approximation as well as a pair-approximation of a stochastic cellular automata model. We provide code for the mean-field approximation, the pair-approximation and the cellular automata online at https://cascade-wp6.github.com/livestock. 

## basic model 

The framework provided by Noy-Meir is a graphical assessment of the attractors of the population dynamics in a simple predator-prey system. It describes mortality and growth as functions of global vegetation cover, $\rho_1$. 

For vegetation mortality, $M$, we assume intrinsic plant mortality, i.e. the inverse of average lifespan, and add the mortality due to grazing risk as a classic type II functional response. 

$$ M(\rho_1) = m \rho_1 + \frac{a \rho_1 L}{1+a h \rho_1} \,,$$

where $m$ denotes the intrinsic mortality rate, $a$ and $h$ are the search efficiency and handling time of the nonlinear functional response (saturating at $1/h$) which is multiplied with the livestock density, $L$. Note that livestock density is defined in the unit number of grazers per area $[\frac{ind.}{ha}]$. Search efficiency $a$ is given in area browsed in per time and grazer individual $[\frac{ha}{y \times ind.}]$, and handling time $h$ is given in time per area consumed $[\frac{y}{ha}]$, which alltogether defines feeding rate as an area consumed per year by a single individual $[\frac{ha}{y \times ind.}]$. The overall change of cover, $M(\rho)$, is thus independent from the size and unit of the observed area $[\frac{1}{y}]$.

The vegetation growth, $G$, is defined as a logistic growth function.

$$ G(\rho_1) = r\rho_1(1-\frac{\rho_1}{K}) \,,$$

where the intrinsic growth rate, $r$, is neutralized when cover approaches the global carrying capacity, $K$. This reflects the global competition of plants fo  resources of homoegeneous distribution, such as space: when all habitable space is occupied, plant growth falls to zero. 

<!-- global feedback mechanisms such as water runoff (negative effect on growth at low cover) or plant refuges against grazing for instance due to fencing (type III funuctional response) might be added here. -->

## local feedbacks

The basic model assumes mortality and growth to be of homogeneous distribution, and neglects spatially-explicit effects. Here, we add plant-plant interactions at the local scale by taking the cover, $q$, in the direct vicinity of plants into account. 
By adding such interactions at the local level into the functions of growth and mortality, patterns emerge that act as positive or negative feedbacks on vegetation cover. 

For vegetation growth, we assume that the local environmental suitability is enhanced by local facilitation (Milchunas et al 1998, Kéfi et al 2007). The reduction in growth rate, $r$, by aridity, i.e. the inverse of environmental quality $b$, is compensated by a function of $q_{0|1}$, the local density of cells in state 1 (i.e. vegetation) given that the focal cell is in state 0 (i.e. empty), and maximizes to one if the cell has four neighbors.

$$ b = b^* + (1 - b^*)  f q_{0|1} \,,$$

with the effect of aridity in absence of local vegetation being increased to the value of $f$ if additive facilitation due to the presence of neighboring plants occurs. This term gradually determines the enhancement of the growth with an increasing local vegetation cover (maximizing at $q_{0|1} = 1$ if the cell has 4 neighbors). 

As an opposing effect, we assume that local competition of plants inhibits colonisation locally by depleting nutrients or light. As cover increases and the interspace areas are closing in, the space available for rejuvenation approaches zero. 
This is assuming that growth is diminished locally by competition, $c$. This affects carrying capacity rather than growth rate itself.

$$ K = K^* (1 - c  q_{0|1})$$

That is, if a cell has a fully vegetated local neighborhood, it's carrying capacity will be reduced by value $c$ ($c \geq K$). 

Regarding plant mortality, we implement two interactions into the model. In sparse environments, high local cover will be attracting grazers and concentrate plant mortality at locations with high local density. We assume that low plant cover reduces search efficiency, $a$, locally by the value $v$

$$ a = a^* + v \frac{q_{1|1}}{\rho_1} $$

Thus, at low local cover feeding will be high on plants with neighbors, whereas at high cover the term has no effect since handling time is limiting consumption. An enhanced search efficiency will raise the critical thresholds for a collapse. 

Opposing to that mechanism, plants in grazed habitats develop protective traits, such as thorns or cushion growth. They thereby provide protected habitat to their direct neighborhood, or share the investments in those traits with their neighbors. Overall grazing mortality thus is reduced through a decrease in local livestock densities by associational resistance, $p$. 

<!--
$$ a = a^{**} (1- p q_{1|1}) $$ 

This causes $a$ to fall to its minimal value ($1-p$) at full local cover. If $p=1$ the feeding is completely neutralized under high local cover, which also causes a drop in grazing mortality if cover is really high.

Combining the attractant decoy and the associational resistance effect yields
<!-- $$ h = h^*  / (1 - p  q_{1|1}) $$

An alternative formulation should be found. The term is highly non-linear and provokes relevant changes only at values above 0.9. It is defined within $(0,1($ 
Instead, we could define associational protection as a reduced impact due to a reduced local density of grazers.
--> 

$$ L = L^* (1 - p  q_{1|1}) $$

<!--
**Update 12.03.2015:** the effect is of less relevance at high cover, since the development of thorns is only induced if local pressure is already high. At high cover it is the handling time limitation that acts as an individual protection. Thus, it makes more sense to implement associational protection as an effect on search efficiency. 

$$ a = a^* (1- p q_{1|1}) $$ 

This causes $a$ to fall to its minimal value ($1-p$) at full local cover. If $p=1$ the feeding is completely neutralized under high local cover, which also causes a drop in grazing mortality if cover is really high. This might be unrealistic, for the biological reasons named above. So, values of $p \leq 0.9$ seem to make sense. 

**Update 26.03.2015:** Also, the formulations of local effects on mortality are unclear about their compatibility, since the attractant effect it is additive while the protective effect is multiplied. 
Thus, I have to specify

$$ a = (a^*  + v q_{1|1} ) (1- p q_{1|1}) $$ 
-->

Since $q_{1|1}$ and $q_{1|0}$ are spatially explicit expressions, these equations are referring to the situation at a particular location in space which is currently in one state or the other. The substitution into $M(\rho)$ and $G(\rho)$ yields transition probabilities, i.e. the probability for death and colonization for the given location, based on the global vegetation cover $\rho_1$ and the local vegetation cover $q_{1|1}$ or $q_{1|0}$ for vegetated or empty locations, respectively:

$$ M(\rho_1,q_{1|1}) = w_{1,0} = m + \frac{(a^*  + v  \frac{q_{1|1}}{\rho_1} ) (1- p q_{1|1}) L \rho_1}{1+ (a^*  + v  \frac{q_{1|1}}{\rho_1} ) (1- p q_{1|1}) h \rho_1} $$

$$ G(\rho_1,q_{1|0}) = w_{0,1} = \frac{r \rho_1 (b^* + (1 - b^*) f q_{0|1}) (1-\frac{\rho_1}{K^* (1 - c q_{0|1})})}{1-\rho_1} $$


Default parameters for the model are provided in table 1. 

parameter | default value | unit   | definition
-----| -----| -------- | ----------------------------------------------
  r  |  1.0 | $[\frac{1}{y}]$  | max. reproduction rate of vegetation per year
  b  |  0.5 | unitless    |environmental quality, a factor that indicates  \newline quality of environment as compared to the best case scenario
  K  |  0.9 | unitless   | carrying capacity of the system, a landscape  \newline specific value that defines the max. potential cover
  f  |  0 | unitless     |  local facilitation, positive effect of plants  \newline  on the colonization probability in their direct neighborhood
  c  |  0 | unitless   | local competition, negative effect of plants on \newline   colonization probability in their direct neighborhood
  m  |  0.05| $[\frac{1}{y}]$   | intrinsic mortality of plants (inverse of av. lifespan)
  v  |  0 | unitless   | attractant-decoy effect, negative effect of plants  \newline  on mortality in their direct neighborhood
  p  |  0 | unitless   | associational resistance, positive protection effects  \newline  of plants on each other against mortality due to grazing
  L  |  2   | $[\frac{ind.}{ha}]$   | Livestock density
  h  |  20  | $[\frac{y}{ha}]$   | handling time, time required to consume one hectar  \newline  of vegetation 
  a  |  10 | $[\frac{ha}{y \times ind.}]$   | search efficiency of livestock, 


## pair-approximation model

Subsequently, we implement these functions into a pair-approximation of a spatially-explicit model. 
The pair-approximation framework (Matsuda et al. 1992) is defined as a system of ordinary differential equations, describing the populations of *pairs* of neighboring locations. By this book-keeping, we also keep track of the average local cover in the neighborhood of vegetated ($q_{1,1}$) and unvegetated ($q_{0,1}$) locations in the landscape. In a two state system, three pairs can be defined with population densities $\rho_{1,1}$ , $\rho_{0,0}$, and $\rho_{0,1}$. Besides, there are the population densities of the singletons, $\rho_0$ and $\rho_1$. 

The following conservation equations allow to calculate population densities of one pair based on the other pairs and singletons:

$$ \rho_1 + \rho_0 = 1$$

$$ \rho_{1,1} + \rho_{0,1} = \rho_1$$

$$ \rho_{0,1} + \rho_{0,0} = \rho_0$$


We now can use the transition probabilities of the individual locations to describe the full system of differential equations.


$$  \frac{\mathrm{d}\rho_{1}}{\mathrm{d}t} = \rho_{0}w_{0,1} - \rho_{1}w_{1,0}   $$

$$  \frac{\mathrm{d}\rho_{1,1}}{\mathrm{d}t} = 2 \rho_{1,0}w_{0,1} - 2 \rho_{1,1} w_{1,0}  $$

$$  \frac{\mathrm{d}\rho_{1,0}}{\mathrm{d}t} = 2 \rho_{0,0}w_{0,1} + 2 \rho_{1,1}w_{1,0} - \rho_{1,0}w_{0,1}    $$

$$  \frac{\mathrm{d}\rho_{0,0}}{\mathrm{d}t} = 2 \rho_{1,0}w_{1,0} - 2 \rho_{0,0}w_{0,1}  $$

$$  \frac{\mathrm{d}\rho_{0}}{\mathrm{d}t} = \rho_{1}w_{1,0} - \rho_{0}w_{0,1} $$

Due to the conservation equations, two of these are sufficient to fully describe the dynamics of the system. 
We chose to keep the first two representing the density of vegetated cells $\rho_1$ and the density of pairs of vegetated cells $\rho_{1,1}$ and subsitute therein $\rho_0 = 1- \rho_1$ and $\rho_{1,0} = \rho_1 - \rho_{1,1}$: 

$$  \frac{\mathrm{d}\rho_{1}}{\mathrm{d}t} = (1-\rho_1) w_{0,1} - \rho_{1}w_{1,0}   $$

$$  \frac{\mathrm{d}\rho_{1,1}}{\mathrm{d}t} = 2 (\rho_1 - \rho_{1,1}) w_{0,1} - 2 \rho_{1,1} w_{1,0}  $$

These two equations are implemented in the package as function `lifestock$pairs()`, which is then called by the ODE-solver. The object `rho` is a list object that contains global cover at first position and global cover of pair (1,1) at second position.

```
    delta_1 = (1-rho[[1]]) * colonization(rho, parms) -
                   rho[[1]] * death(rho, parms)
    delta_11 = 2 * (rho[[1]]-rho[[2]]) * colonization(rho, parms) - 
                   2 * rho[[2]] * death(rho, parms)

```

The functions `colonization()` and `death()` are defined in `R/definitions.R`
 
<!--
$$  \frac{\mathrm{d}\rho_{11}}{\mathrm{d}t} = 2 \rho_{10} \frac{r \rho_1^{1+\alpha} (b^* + (1 - b) f q_{0|1})) (1-\frac{\rho_1}{K^* (1 - c q_{0|1})})}{1-\rho_1} - 2 \rho_{11} m -  2 \rho_{11} \frac{(a^*  + v q_{1|1})L^* (1 - p  q_{1|1})\rho_1^{q}}{1+(a^*  + v q_{1|1})h\rho_1^{1+q}}  $$

$$  \frac{\mathrm{d}\rho_{1}}{\mathrm{d}t} = \rho_{0}\frac{r \rho_1^{1+\alpha} (b^* + (1 - b)  f q_{0|1})) (1-\frac{\rho_1}{K^* (1 - c q_{0|1})})}{1-\rho_1} - \rho_{1}m - \frac{(a^*  + v q_{1|1})L^* (1 - p  q_{1|1})\rho_1^{1+q}}{1+(a^*  + v q_{1|1})h\rho_1^{1+q}}   $$

they can be simplified to 


$$  \frac{\mathrm{d}\rho_{11}}{\mathrm{d}t} = 2 \rho_{10} \frac{r \rho_1^{1+\alpha} (b^* + (1 - b)  f q_{0|1})) (1-\frac{\rho_1}{K^* (1 - c q_{0|1})})}{1-\rho_1} - 2 \rho_{11} m -  2 \rho_{11} \frac{(a^*  + v q_{1|1})L^* (1 - p  q_{1|1}) \rho_1^{q}}{1+(a^*  + v q_{1|1})h)\rho_1^{1+q}}  $$

$$  \frac{\mathrm{d}\rho_{1}}{\mathrm{d}t} = r \rho_1^{1+\alpha} (b^* + (1 - b)  f q_{0|1})) (1-\frac{\rho_1}{K^* (1 - c q_{0|1})}) - \rho_{1}m - \frac{(a^*  + v q_{1|1})L^* (1 - p  q_{1|1})\rho_1^{1+q}}{1+(a^*  + v q_{1|1})h\rho_1^{1+q}}   $$
 

as a matter of fact the equation for $\frac{\mathrm{d}\rho_{1}}{\mathrm{d}t}$ will re-convert into the regular population equation. 
-->
To substitute the transition probabilities $M(\rho_1,q_{1|1}) = w_{1,0}$ and $G(\rho_1,q_{1|0}) = w_{0,1}$ in these equtions, we require definitions of local cover in the terms of the pair-approximation framework. 
Since formally $q_{i|j}$ is a conditional probability (given that one neighbor is in state $i$, what is the probability to find the other in state $j$) we can express it in terms of densities of pairs and ‘singletons,’ as  

$$ q_{i|j} = \frac{\rho_{ij}}{\rho_i} $$

thus,

$$ q_{0|1} = \frac{\rho_{10}}{\rho_0} =  \frac{\rho_{1} - \rho_{11}}{1 - \rho_1} $$

$$ q_{1|1} = \frac{\rho_{11}}{\rho_1} $$


Now, substitution yields

$$  \frac{\mathrm{d}\rho_{11} }{\mathrm{d}t} = 2 (\rho_1 - \rho_{11}) \frac{r \rho_1^{1+\alpha} (b^* + (1 - b)  f \frac{\rho_{1} - \rho_{11}}{1 - \rho_1} )) (1-\frac{\rho_1}{K^* (1 - c \frac{\rho_{1} - \rho_{11}}{1 - \rho_1})})}{1-\rho_1} - 2 \rho_{11} m -  2 \rho_{11} \frac{(a^*  + v \frac{\rho_{11}}{\rho_1})L^* (1 - p \frac{\rho_{11}}{\rho_1})\rho_1^{q}}{1+(a^*  + v \frac{\rho_{11}}{\rho_1})h\rho_1^{1+q}}  $$

$$  \frac{\mathrm{d}\rho_{1}}{\mathrm{d}t} = r \rho_1^{1+\alpha} (b^* + (1 - b) f  \frac{\rho_{1} - \rho_{11}}{1 - \rho_1}) (1-\frac{\rho_1}{K^* (1 - c \frac{\rho_{1} - \rho_{11}}{1 - \rho_1})}) - \rho_{1}m -  \frac{(a^*  + v \frac{\rho_{11}}{\rho_1})L^* (1 - p \frac{\rho_{11}}{\rho_1})\rho_1^{1+q}}{1+(a^*  + v \frac{\rho_{11}}{\rho_1})h\rho_1^{1+q}}   $$




# References

Kéfi, S., M. Rietkerk, M. van Baalen, and M. Loreau. 2007. Local facilitation, bistability and transitions in arid ecosystems. Theoretical Population Biology 71:367–379.

Milchunas, D. G., W. K. Lauenroth, and I. C. Burke. 1998. Livestock grazing: animal and plant biodiversity of shortgrass steppe and the relationship to ecosystem function. Oikos:65–74.

Matsuda, H., N. Ogita, A. Sasaki, and K. Sato. 1992. Statistical Mechanics of Population: The Lattice Lotka-Volterra Model. Progress of Theoretical Physics 88:1035–1049.
